/*
SQLyog v10.2 
MySQL - 5.7.16 : Database - onlyknow_platform
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`onlyknow_platform` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `onlyknow_platform`;

/*Table structure for table `app_info` */

DROP TABLE IF EXISTS `app_info`;

CREATE TABLE `app_info` (
  `APP_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `APP_VERSION` VARCHAR(200) NOT NULL,
  `APP_NAME` VARCHAR(200) NOT NULL,
  `APP_URL` VARCHAR(200) NOT NULL,
  `APP_DESCRIBE` TEXT,
  `APP_UA` TEXT,
  `APP_IMAGE_URL` VARCHAR(200) DEFAULT NULL,
  `APP_SIZE` VARCHAR(200) NOT NULL,
  `APP_IS_MANDATORY` TINYINT(1) NOT NULL,
  `APP_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`APP_ID`)
) ENGINE=INNODB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

/*Table structure for table `card_browsing` */

DROP TABLE IF EXISTS `card_browsing`;

CREATE TABLE `card_browsing` (
  `CB_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `CARD_ID` INT(11) NOT NULL,
  `USER_NAME` VARCHAR(200) NOT NULL,
  `CB_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`CB_ID`)
) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

/*Table structure for table `card_info` */

DROP TABLE IF EXISTS `card_info`;

CREATE TABLE `card_info` (
  `CARD_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `CARD_TYPE` VARCHAR(200) NOT NULL,
  `USER_NAME` VARCHAR(200) NOT NULL,
  `TITLE_TEXT` VARCHAR(200) NOT NULL,
  `TITLE_IMAGE_URL` VARCHAR(200) DEFAULT NULL,
  `CONTENT_IMAGE_URL` TEXT,
  `CONTENT_TITLE_TEXT` TEXT,
  `CONTENT_TEXT` TEXT,
  `LABELLING` VARCHAR(200) DEFAULT NULL,
  `MESSAGE_LINK` VARCHAR(200) DEFAULT NULL,
  `PRAISE_COUNT` INT(11) DEFAULT '0',
  `WATCH_COUNT` INT(11) DEFAULT '0',
  `COMMENT_COUNT` INT(11) DEFAULT '0',
  `BROWSING_COUNT` INT(11) DEFAULT '0',
  `APPROVE_BY` INT(2) NOT NULL,
  `APPROVE_INFO` TEXT,
  `CREATE_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`CARD_ID`)
) ENGINE=INNODB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

/*Table structure for table `comment` */

DROP TABLE IF EXISTS `comment`;

CREATE TABLE `comment` (
  `COM_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(200) NOT NULL,
  `CARD_ID` INT(11) NOT NULL,
  `MESSAGE` TEXT,
  `COM_PRAISE` INT(11) DEFAULT '0',
  `COM_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`COM_ID`)
) ENGINE=INNODB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;

/*Table structure for table `comment_reply` */

DROP TABLE IF EXISTS `comment_reply`;

CREATE TABLE `comment_reply` (
  `COMR_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `COM_ID` INT(11) NOT NULL,
  `USER_NAME` VARCHAR(200) NOT NULL,
  `MESSAGE` TEXT,
  `COMR_PRAISE` INT(11) DEFAULT '0',
  `COMR_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`COMR_ID`)
) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

/*Table structure for table `feedback` */

DROP TABLE IF EXISTS `feedback`;

CREATE TABLE `feedback` (
  `FB_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(200) NOT NULL,
  `FB_DESCRIBE` TEXT NOT NULL,
  `FB_IMAGE` MEDIUMTEXT,
  `FB_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`FB_ID`)
) ENGINE=INNODB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

/*Table structure for table `goods` */

DROP TABLE IF EXISTS `goods`;

CREATE TABLE `goods` (
  `GD_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `GD_NAME` VARCHAR(200) NOT NULL,
  `GD_TYPE` VARCHAR(200) DEFAULT NULL,
  `GD_DESCRIBE` TEXT,
  `GD_PRICE` INT(11) NOT NULL,
  `GD_INTRODUCTION` VARCHAR(200) NOT NULL,
  `GD_ICON_URL` VARCHAR(200) NOT NULL,
  `GD_IMAGE_URL` VARCHAR(200) NOT NULL,
  `GD_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`GD_ID`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

/*Table structure for table `goods_purchase_history` */

DROP TABLE IF EXISTS `goods_purchase_history`;

CREATE TABLE `goods_purchase_history` (
  `PR_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `GD_ID` INT(11) NOT NULL,
  `USER_NAME` VARCHAR(200) NOT NULL,
  `PR_CONSUME` INT(11) NOT NULL,
  `PR_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`PR_ID`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

/*Table structure for table `image_carousel_ad` */

DROP TABLE IF EXISTS `image_carousel_ad`;

CREATE TABLE `image_carousel_ad` (
  `GROUP_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `HP_IMAGE_URL1` VARCHAR(200) DEFAULT NULL,
  `HP_IMAGE_URL2` VARCHAR(200) DEFAULT NULL,
  `HP_IMAGE_URL3` VARCHAR(200) DEFAULT NULL,
  `HP_IMAGE_URL4` VARCHAR(200) DEFAULT NULL,
  `HP_IMAGE_URL5` VARCHAR(200) DEFAULT NULL,
  `AD_IMAGE_URL1` VARCHAR(200) DEFAULT NULL,
  `AD_IMAGE_URL2` VARCHAR(200) DEFAULT NULL,
  `AD_IMAGE_URL3` VARCHAR(200) DEFAULT NULL,
  `AD_LINK_URL1` VARCHAR(200) DEFAULT NULL,
  `AD_LINK_URL2` VARCHAR(200) DEFAULT NULL,
  `AD_LINK_URL3` VARCHAR(200) DEFAULT NULL,
  `GROUP_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`GROUP_ID`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

/*Table structure for table `praise_card` */

DROP TABLE IF EXISTS `praise_card`;

CREATE TABLE `praise_card` (
  `CP_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(200) NOT NULL,
  `CARD_ID` INT(11) NOT NULL,
  `CP_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`CP_ID`)
) ENGINE=INNODB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

/*Table structure for table `praise_comment` */

DROP TABLE IF EXISTS `praise_comment`;

CREATE TABLE `praise_comment` (
  `CP_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(200) NOT NULL,
  `COM_ID` INT(11) NOT NULL,
  `CP_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`CP_ID`)
) ENGINE=INNODB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

/*Table structure for table `praise_commentreply` */

DROP TABLE IF EXISTS `praise_commentreply`;

CREATE TABLE `praise_commentreply` (
  `CRP_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(200) NOT NULL,
  `COMR_ID` INT(11) NOT NULL,
  `CRP_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`CRP_ID`)
) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

/*Table structure for table `report` */

DROP TABLE IF EXISTS `report`;

CREATE TABLE `report` (
  `RP_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(200) NOT NULL,
  `RP_TYPE` VARCHAR(200) NOT NULL,
  `PASSIVE_ID` INT(11) NOT NULL,
  `RP_MESSAGE` TEXT NOT NULL,
  `RP_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`RP_ID`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

/*Table structure for table `user_attention` */

DROP TABLE IF EXISTS `user_attention`;

CREATE TABLE `user_attention` (
  `UAT_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME_MAIN` VARCHAR(200) NOT NULL,
  `USER_NAME_RETE` VARCHAR(200) NOT NULL,
  `UAT_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`UAT_ID`)
) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

/*Table structure for table `user_info` */

DROP TABLE IF EXISTS `user_info`;

CREATE TABLE `user_info` (
  `USER_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(200) NOT NULL,
  `USER_NICKNAME` VARCHAR(200) NOT NULL,
  `USER_TYPE` VARCHAR(200) NOT NULL,
  `USER_PASSWORD` VARCHAR(200) NOT NULL,
  `USER_PHONE` VARCHAR(200) NOT NULL,
  `USER_EMAIL` VARCHAR(200) NOT NULL,
  `SEX` VARCHAR(200) DEFAULT NULL,
  `AGE` INT(5) DEFAULT NULL,
  `BIRTH_DATE` DATE DEFAULT NULL,
  `HEAD_PORTRAIT_URL` VARCHAR(200) DEFAULT NULL,
  `HOMEPAGE_URL` VARCHAR(200) DEFAULT NULL,
  `TAG` VARCHAR(200) DEFAULT '这个人很懒,什么都没有留下!',
  `ME_WATCH` INT(11) DEFAULT '0',
  `ME_ATTENTION` INT(11) DEFAULT '0',
  `ME_INTEGRAL` INT(11) DEFAULT '0',
  `ME_ARTICLE` INT(11) DEFAULT '0',
  `WITHOUT_APPROVA` TINYINT(1) NOT NULL DEFAULT '0',
  `EDIT_DATE` DATETIME DEFAULT NULL,
  `RE_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=INNODB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

/*Table structure for table `user_location` */

DROP TABLE IF EXISTS `user_location`;

CREATE TABLE `user_location` (
  `UL_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(200) NOT NULL,
  `UL_LONGITUDE` DOUBLE NOT NULL,
  `UL_DIMENSION` DOUBLE NOT NULL,
  `UL_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`UL_ID`)
) ENGINE=INNODB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

/*Table structure for table `user_watch` */

DROP TABLE IF EXISTS `user_watch`;

CREATE TABLE `user_watch` (
  `UW_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(200) NOT NULL,
  `CARD_ID` INT(11) NOT NULL,
  `UW_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`UW_ID`)
) ENGINE=INNODB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
